export const constsHeaderNav = [
"ANIMALES Y PLANTAS",
"APPS Y SOFTWARE",
"BELLEZA Y MODA",
"CULINARIA Y GASTRONOMÍA",
"DESARROLLO PERSONAL",
"EDUCACIÓN",
"ENTRETENIMIENTO Y HOBBIES",
"ESPIRITUALIDAD",
"FINANZAS E INVERSIÓN",
"IDIOMAS",
"MÚSICA Y ARTES",
"NEGOCIOS Y MARKETING",
"SALUD Y DEPORTES",
"OTROS"
]